

# A list of assignees, overrides reviewers if set
assignees:
   - ymodak
   - jvishnuvardhan
   - lvenugopalan
   
compiler_assignees:
   - rthadur
Comment: >
   From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries:

      * For TF-GPU - See point 1
      * For TF-CPU - See point 2

   -----------------------------------------------------------------------------------------------

   **1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**

   Make sure you are using compatible TF and CUDA versions.
   Please refer following TF version and CUDA version compatibility table.

   | TF  | CUDA |
   | :-------------: | :-------------: |
   | 2.1.0 - 2.2.0  | 10.1 |
   | 1.13.1 - 2.0  | 10.0  |
   | 1.5.0 - 1.12.0 | 9.0 |

   * If you have above configuration and using _**Windows**_ platform -
   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
    * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
   * If you have above configuration and using _**Ubuntu/Linux**_ platform -
   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH environment variable.
    * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).
   * If error still persists then, apparently your CPU model does not support AVX instruction sets.
   * Refer [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).

   
